/**
 * Dev Jokes API
 * A free API for developer jokes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DevJokesApi);
  }
}(this, function(expect, DevJokesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DevJokesApi.Joke();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Joke', function() {
    it('should create an instance of Joke', function() {
      // uncomment below and update the code to test Joke
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be.a(DevJokesApi.Joke);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be();
    });

    it('should have the property setup (base name: "setup")', function() {
      // uncomment below and update the code to test the property setup
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be();
    });

    it('should have the property punchline (base name: "punchline")', function() {
      // uncomment below and update the code to test the property punchline
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be();
    });

    it('should have the property difficulty (base name: "difficulty")', function() {
      // uncomment below and update the code to test the property difficulty
      //var instance = new DevJokesApi.Joke();
      //expect(instance).to.be();
    });

  });

}));
