/**
 * Dev Jokes API
 * A free API for developer jokes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DevJokesApi);
  }
}(this, function(expect, DevJokesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DevJokesApi.JokesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JokesApi', function() {
    describe('apiJokesCategoryCategoryGet', function() {
      it('should call apiJokesCategoryCategoryGet successfully', function(done) {
        //uncomment below and update the code to test apiJokesCategoryCategoryGet
        //instance.apiJokesCategoryCategoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiJokesDifficultyLevelGet', function() {
      it('should call apiJokesDifficultyLevelGet successfully', function(done) {
        //uncomment below and update the code to test apiJokesDifficultyLevelGet
        //instance.apiJokesDifficultyLevelGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiJokesGet', function() {
      it('should call apiJokesGet successfully', function(done) {
        //uncomment below and update the code to test apiJokesGet
        //instance.apiJokesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiJokesIdGet', function() {
      it('should call apiJokesIdGet successfully', function(done) {
        //uncomment below and update the code to test apiJokesIdGet
        //instance.apiJokesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiJokesRandomGet', function() {
      it('should call apiJokesRandomGet successfully', function(done) {
        //uncomment below and update the code to test apiJokesRandomGet
        //instance.apiJokesRandomGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
