/**
 * Dev Jokes API
 * A free API for developer jokes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Statistics model module.
 * @module model/Statistics
 * @version 1.0.0
 */
class Statistics {
    /**
     * Constructs a new <code>Statistics</code>.
     * @alias module:model/Statistics
     */
    constructor() { 
        
        Statistics.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Statistics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Statistics} obj Optional instance to populate.
     * @return {module:model/Statistics} The populated <code>Statistics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Statistics();

            if (data.hasOwnProperty('uptime')) {
                obj['uptime'] = ApiClient.convertToType(data['uptime'], 'Number');
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], 'Number');
            }
            if (data.hasOwnProperty('lastDowntime')) {
                obj['lastDowntime'] = ApiClient.convertToType(data['lastDowntime'], 'String');
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Statistics</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Statistics</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['lastDowntime'] && !(typeof data['lastDowntime'] === 'string' || data['lastDowntime'] instanceof String)) {
            throw new Error("Expected the field `lastDowntime` to be a primitive type in the JSON string but got " + data['lastDowntime']);
        }

        return true;
    }


}



/**
 * API uptime in seconds
 * @member {Number} uptime
 */
Statistics.prototype['uptime'] = undefined;

/**
 * Total number of requests
 * @member {Number} requests
 */
Statistics.prototype['requests'] = undefined;

/**
 * Last recorded downtime
 * @member {String} lastDowntime
 */
Statistics.prototype['lastDowntime'] = undefined;

/**
 * API start time
 * @member {Date} startedAt
 */
Statistics.prototype['startedAt'] = undefined;






export default Statistics;

