/**
 * Dev Jokes API
 * A free API for developer jokes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Statistics from '../model/Statistics';

/**
* Statistics service.
* @module api/StatisticsApi
* @version 1.0.0
*/
export default class StatisticsApi {

    /**
    * Constructs a new StatisticsApi. 
    * @alias module:api/StatisticsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiStatisticsGet operation.
     * @callback module:api/StatisticsApi~apiStatisticsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Statistics} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get API usage statistics
     * @param {module:api/StatisticsApi~apiStatisticsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Statistics}
     */
    apiStatisticsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Statistics;
      return this.apiClient.callApi(
        '/api/statistics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
